name: portfolio

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0.1.2
        with:
          buildMode: release
          toolchain: stable
          outDirectory: target/dx/portfolio/release/web/public
          rootPath: .
